function out=detector_out(psf,x2,y2,detector_par)
%psf is the point spread function of lens,x2,y2 is the coordinate of psf
%d is the sample interval of the psf
%detector_par is the parement of the detector, generated by detector_setting  
d=abs(y2(6,6)-y2(5,6)); % assume square
ratio = detector_par.pitch/d;
%cal detector integration kernal
int_ratio = floor(ratio);
x = (-1:int_ratio)-floor(int_ratio/2);
H = ones(length(x));
H(1,:) = H(1,:).*(ratio-int_ratio)/2;
H(end,:) = H(end,:).*(ratio-int_ratio)/2;
H(:,1) = H(:,1).*(ratio-int_ratio)/2;
H(:,end) = H(:,end).*(ratio-int_ratio)/2;
%cal new psf
new_psf = conv2(psf,H,'same');

%cal detector output
out=interp2(x2, y2, new_psf, detector_par.PX, detector_par.PY); 







